name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'biskit'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello!
    - name: echo inputs
      run: | 
        echo ${{ inputs.name }}
        echo ${{ inputs.environment }}
